<h1>HDB Dataset</h1>

<table border="1">
  <tbody>
    <tr>
      <td>Name</td>
      <td>Toh Jun Long</td>
    </tr>
    <tr>
      <td>Date</td>
      <td>13/09/2026</td>
    </tr>
  </tbody>
</table>

<p href='https://data.gov.sg/collections/189/view'>https://data.gov.sg/collections/189/view</p>


Data type:
<li>Month: Month (YYYY-MM)</li>
<li>Town: Text</li>
<li>Flat Type: Text</li>
<li>Block: Text</li>
<li>Street Name: Text</li>
<li>Storey Range: Text</li>
<li>Floor Area: Numeric</li>
<li>Flat Model: Text</li>
<li>Lease Commencement Date: Year (YYYY)</li>
<li>Resale Price: Numeric</li>

In [5]:
# Importing relevant libraries
import pandas as pd # For easier reading of the csv files
import matplotlib
import seaborn as sns
import os, sys

In [16]:
hdb_mar2012_dec2014 = pd.read_csv('.\HDB\Raw\Resale Flat Prices (Based on Registration Date), From Mar 2012 to Dec 2014.csv')
hdb_mar2012_dec2014.head()

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,resale_price
0,2012-03,ANG MO KIO,2 ROOM,172,ANG MO KIO AVE 4,06 TO 10,45.0,Improved,1986,250000.0
1,2012-03,ANG MO KIO,2 ROOM,510,ANG MO KIO AVE 8,01 TO 05,44.0,Improved,1980,265000.0
2,2012-03,ANG MO KIO,3 ROOM,610,ANG MO KIO AVE 4,06 TO 10,68.0,New Generation,1980,315000.0
3,2012-03,ANG MO KIO,3 ROOM,474,ANG MO KIO AVE 10,01 TO 05,67.0,New Generation,1984,320000.0
4,2012-03,ANG MO KIO,3 ROOM,604,ANG MO KIO AVE 5,06 TO 10,67.0,New Generation,1980,321000.0

In [27]:
hdb_mar2012_dec2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52203 entries, 0 to 52202
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                52203 non-null  object
 1   town                 52203 non-null  object
 2   flat_type            52203 non-null  object
 3   block                52203 non-null  object
 4   street_name          52203 non-null  object
 5   storey_range         52203 non-null  object
 6   floor_area_sqm       52203 non-null  int32
 7   flat_model           52203 non-null  object
 8   lease_commence_date  52203 non-null  int64
 9   resale_price         52203 non-null  float64
dtypes: float64(1), int32(1), int64(1), object(7)
memory usage: 3.8+ MB

In [28]:
# attempt to convert following columns to int to detect any decimal point: floor_area_sqm, resale_price
hdb_mar2012_dec2014['floor_area_sqm'] = hdb_mar2012_dec2014['floor_area_sqm'].astype('int')
hdb_mar2012_dec2014['resale_price'] = hdb_mar2012_dec2014['resale_price'].astype('int')
hdb_mar2012_dec2014.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52203 entries, 0 to 52202
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                52203 non-null  object
 1   town                 52203 non-null  object
 2   flat_type            52203 non-null  object
 3   block                52203 non-null  object
 4   street_name          52203 non-null  object
 5   storey_range         52203 non-null  object
 6   floor_area_sqm       52203 non-null  int32
 7   flat_model           52203 non-null  object
 8   lease_commence_date  52203 non-null  int64
 9   resale_price         52203 non-null  int32
dtypes: int32(2), int64(1), object(7)
memory usage: 3.6+ MB

In [22]:
hdb_jan2015_dec2016 = pd.read_csv('.\HDB\Raw\Resale Flat Prices (Based on Registration Date), From Jan 2015 to Dec 2016.csv')
hdb_jan2015_dec2016.head(100)

,month,town,flat_type,block,street_name,storey_range,floor_area_sqm,flat_model,lease_commence_date,remaining_lease,resale_price
0,2015-01,ANG MO KIO,3 ROOM,174,ANG MO KIO AVE 4,07 TO 09,60.0,Improved,1986,70,255000.0
1,2015-01,ANG MO KIO,3 ROOM,541,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1981,65,275000.0
2,2015-01,ANG MO KIO,3 ROOM,163,ANG MO KIO AVE 4,01 TO 03,69.0,New Generation,1980,64,285000.0
3,2015-01,ANG MO KIO,3 ROOM,446,ANG MO KIO AVE 10,01 TO 03,68.0,New Generation,1979,63,290000.0
4,2015-01,ANG MO KIO,3 ROOM,557,ANG MO KIO AVE 10,07 TO 09,68.0,New Generation,1980,64,290000.0
...,...,...,...,...,...,...,...,...,...,...,...
95,2015-01,BEDOK,3 ROOM,401,BEDOK NTH AVE 3,10 TO 12,67.0,New Generation,1979,63,332000.0
96,2015-01,BEDOK,3 ROOM,2,BEDOK STH AVE 1,07 TO 09,65.0,Improved,1976,60,338000.0
97,2015-01,BEDOK,3 ROOM,2,BEDOK STH AVE 1,10 TO 12,65.0,Improved,1976,60,339000.0
98,2015-01,BEDOK,3 ROOM,426,BEDOK NTH RD,10 TO 12,67.0,New Generation,1979,63,342000.0
99,2015-01,BEDOK,3 ROOM,116,BEDOK NTH RD,07 TO 09,73.0,New Generation,1978,62,355000.0

In [19]:
hdb_jan2015_dec2016.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37153 entries, 0 to 37152
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   month                37153 non-null  object
 1   town                 37153 non-null  object
 2   flat_type            37153 non-null  object
 3   block                37153 non-null  object
 4   street_name          37153 non-null  object
 5   storey_range         37153 non-null  object
 6   floor_area_sqm       37153 non-null  float64
 7   flat_model           37153 non-null  object
 8   lease_commence_date  37153 non-null  int64
 9   remaining_lease      37153 non-null  int64
 10  resale_price         37153 non-null  float64
dtypes: float64(2), int64(2), object(7)
memory usage: 3.1+ MB